/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/3d-models/HexTileGrass.glb -t 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    HexTileGrass: THREE.Mesh;
  };
  materials: {
    MGrassMat: THREE.MeshStandardMaterial;
  };
};

export function HexTileGrass(props: JSX.IntrinsicElements["mesh"]) {
  const { nodes, materials } = useGLTF(
    "/3d-models/HexTileGrass.glb",
  ) as GLTFResult;

  return (
    <mesh
      {...props}
      dispose={null}
      receiveShadow
      name="HexTileGrass"
      geometry={nodes.HexTileGrass.geometry}
      material={materials.MGrassMat}
    />
  );
}

useGLTF.preload("/3d-models/HexTileGrass.glb");
