export function GraphDiagram() {
  return (
    <svg
      viewBox="0 0 600 600"
      xmlns="http://www.w3.org/2000/svg"
      className="max-w-screen-sm h-fit"
    >
      <g transform="scale(100, 100) translate(-0.75, -0.5)">
        <line
          className="stroke-emerald-500"
          strokeWidth="0.1"
          x1="3"
          y1="2"
          x2="4"
          y2="2"
        ></line>
        <line
          className="stroke-emerald-500"
          strokeWidth="0.1"
          x1="4"
          y1="2"
          x2="4"
          y2="3"
        ></line>
        <line
          className="stroke-emerald-500"
          strokeWidth="0.1"
          x1="4"
          y1="3"
          x2="3"
          y2="3"
        ></line>
        <line
          className="stroke-emerald-500"
          strokeWidth="0.1"
          x1="3"
          y1="2"
          x2="3"
          y2="3"
        ></line>
        <line
          className="stroke-emerald-500"
          strokeWidth="0.1"
          x1="3"
          y1="2"
          x2="1"
          y2="2"
        ></line>
        <line
          className="stroke-emerald-500"
          strokeWidth="0.1"
          x1="4"
          y1="2"
          x2="5"
          y2="1"
        ></line>
        <line
          className="stroke-emerald-500"
          strokeWidth="0.1"
          x1="4"
          y1="3"
          x2="6"
          y2="3"
        ></line>
        <line
          className="stroke-emerald-500"
          strokeWidth="0.1"
          x1="6"
          y1="3"
          x2="5"
          y2="1"
        ></line>
        <circle
          className="fill-indigo-500 stroke-indigo-500"
          r="0.2"
          strokeWidth="0.02"
          cx="3"
          cy="2"
        ></circle>
        <circle
          className="fill-indigo-500 stroke-indigo-500"
          r="0.2"
          strokeWidth="0.02"
          cx="4"
          cy="2"
        ></circle>
        <circle
          className="fill-indigo-500 stroke-indigo-500"
          r="0.2"
          strokeWidth="0.02"
          cx="4"
          cy="3"
        ></circle>
        <circle
          className="fill-indigo-500 stroke-indigo-500"
          r="0.2"
          strokeWidth="0.02"
          cx="3"
          cy="3"
        ></circle>
        <circle
          className="fill-indigo-500 stroke-indigo-500"
          r="0.2"
          strokeWidth="0.02"
          cx="6"
          cy="3"
        ></circle>
        <circle
          className="fill-indigo-500 stroke-indigo-500"
          r="0.2"
          strokeWidth="0.02"
          cx="5"
          cy="1"
        ></circle>
        <circle
          className="fill-indigo-500 stroke-indigo-500"
          r="0.2"
          strokeWidth="0.02"
          cx="1"
          cy="2"
        ></circle>
        <text
          className="fill-slate-50"
          textAnchor="middle"
          fontSize="0.25"
          x="3"
          y="2.08"
        >
          A
        </text>
        <text
          className="fill-slate-50"
          textAnchor="middle"
          fontSize="0.25"
          x="4"
          y="2.08"
        >
          B
        </text>
        <text
          className="fill-slate-50"
          textAnchor="middle"
          fontSize="0.25"
          x="4"
          y="3.08"
        >
          C
        </text>
        <text
          className="fill-slate-50"
          textAnchor="middle"
          fontSize="0.25"
          x="3"
          y="3.08"
        >
          D
        </text>
        <text
          className="fill-slate-50"
          textAnchor="middle"
          fontSize="0.25"
          x="6"
          y="3.08"
        >
          E
        </text>
        <text
          className="fill-slate-50"
          textAnchor="middle"
          fontSize="0.25"
          x="5"
          y="1.08"
        >
          F
        </text>
        <text
          className="fill-slate-50"
          textAnchor="middle"
          fontSize="0.25"
          x="1"
          y="2.08"
        >
          G
        </text>
      </g>
    </svg>
  );
}
