/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/3d-models/HexTile.glb -t -r ./src/assets 
*/

import { useRef } from "react";
import * as THREE from "three";
import { useGLTF, useHelper } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh;
  };
};

export function HexTileModel(props: JSX.IntrinsicElements["group"]) {
  // eslint-disable-next-line
  // @ts-ignore
  const { nodes } = useGLTF("/3d-models/HexTile.glb") as GLTFResult;

  console.log(nodes.Cylinder.geometry);
  // isSphere: true
  // center: {x: 0, y: 0, z: 0}
  // 0.7348821301486452

  // console.log(nodes.Cylinder.geometry.boundingBox.max);
  // const boundingBox = {
  //   x: 0.48095351457595825,
  //   y: 0.017713172361254692,
  //   z: 0.5553572773933411,
  // };

  const tileMeshRef = useRef(null);

  // eslint-disable-next-line
  // @ts-ignore
  useHelper(tileMeshRef, THREE.BoxHelper, "cyan");

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={tileMeshRef}
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        rotation={[0, Math.PI / 2, 0]}
      >
        <meshStandardMaterial
          attach="material"
          color={"teal"}
          roughness={0.4}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/3d-models/HexTile.glb");
