/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/3d-models/HexTile.glb -t -r ./src/assets 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh;
  };
};

export function HexTileModel(props: JSX.IntrinsicElements["group"]) {
  // eslint-disable-next-line
  // @ts-ignore
  const { nodes } = useGLTF("/3d-models/HexTile.glb") as GLTFResult;

  // nodes.Cylinder.geometry.boundingSphere.radius
  // 0.7348821301486452

  console.log(nodes.Cylinder.geometry);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        rotation={[0, Math.PI / 2, 0]}
      >
        <meshStandardMaterial
          attach="material"
          color={"teal"}
          roughness={0.4}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/3d-models/HexTile.glb");
