/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/3DModels/3DModels/UnrealSimpleMannequin.glb -t 
*/

import * as THREE from "three";
import { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    SKM_Manny_Simple_LOD1006: THREE.SkinnedMesh;
    SKM_Manny_Simple_LOD1006_1: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    ["MI_Manny_01.006"]: THREE.MeshStandardMaterial;
    ["MI_Manny_02.006"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName =
  | "Armature.001|mixamo.com|Layer0"
  | "Armature|mixamo.com|Layer0"
  | "Armature|mixamo.com|Layer0.001"
  | "Armature|mixamo.com|Layer0.002";
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "/3DModels/UnrealSimpleMannequin.glb",
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  console.log(actions);

  useEffect(() => {
    actions["Armature.001|mixamo.com|Layer0"]?.play();
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="SKM_Manny_Simple_LOD1">
            <skinnedMesh
              name="SKM_Manny_Simple_LOD1006"
              geometry={nodes.SKM_Manny_Simple_LOD1006.geometry}
              material={materials["MI_Manny_01.006"]}
              skeleton={nodes.SKM_Manny_Simple_LOD1006.skeleton}
            />
            <skinnedMesh
              name="SKM_Manny_Simple_LOD1006_1"
              geometry={nodes.SKM_Manny_Simple_LOD1006_1.geometry}
              material={materials["MI_Manny_02.006"]}
              skeleton={nodes.SKM_Manny_Simple_LOD1006_1.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3DModels/UnrealSimpleMannequin.glb");
